import { Button, VerticalBox, StandardTableView } from "std-widgets.slint";

export component HelloWorld {
    height: 600px;
    width: 800px;
    VerticalBox {
        alignment: start;
        HorizontalLayout {
            alignment: center;
            StandardTableView {
                width: 400px;
                height: 400px;
                columns: [
                    {title: "Title"},
                    {title: "Value"},
                ];
                rows: [
                    [{text: "X"},{text: "0"}],
                    [{text: "Y"},{text: "0"}],
                    [{text: "Z"},{text: "0"}],
                    [{text: "R"},{text: "0"}],
                    [{text: "G"},{text: "0"}],
                    [{text: "B"},{text: "0"}],
                    [{text: "LUX"},{text: "0"}],                    
                ];

            }
        }
        /*   
        Text {
            text: "Hello World!";
            font-size: 2rem;
            horizontal-alignment: center;
        }
        HorizontalLayout {
            alignment: center;
            Button { text: "OK"; }
        }
        */
    }
}
